const videos = {
    Html: [
      { index: 1, title: 'HTML Kirish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXIuQ1FolMvVw32MCfcSToQ4H0Y8PvRS87w&s',videoUrl:'https://www.youtube.com/watch?v=XfyqcNbx91w&t=385s' },
      { index: 2, title: 'HTML Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXIuQ1FolMvVw32MCfcSToQ4H0Y8PvRS87w&s',videoUrl:'https://www.youtube.com/watch?v=XfyqcNbx91w&t=385s'  },
      { index: 3, title: 'HTML Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXIuQ1FolMvVw32MCfcSToQ4H0Y8PvRS87w&s',videoUrl:'https://www.youtube.com/watch?v=XfyqcNbx91w&t=385s'  },
      { index: 1, title: 'HTML Kirish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXIuQ1FolMvVw32MCfcSToQ4H0Y8PvRS87w&s',videoUrl:'https://www.youtube.com/watch?v=XfyqcNbx91w&t=385s'  },
      { index: 2, title: 'HTML Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXIuQ1FolMvVw32MCfcSToQ4H0Y8PvRS87w&s',videoUrl:'https://www.youtube.com/watch?v=XfyqcNbx91w&t=385s'  },
      { index: 3, title: 'HTML Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXXIuQ1FolMvVw32MCfcSToQ4H0Y8PvRS87w&s',videoUrl:'https://www.youtube.com/watch?v=XfyqcNbx91w&t=385s'  },
    ],
    Css: [
      { index: 1, title: 'CSS Kirish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vkYQ-fp4xFS6EK2qy4ntaox3x81ziRTV6Q&s' },
      { index: 2, title: 'CSS Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vkYQ-fp4xFS6EK2qy4ntaox3x81ziRTV6Q&s' },
      { index: 3, title: 'CSS Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vkYQ-fp4xFS6EK2qy4ntaox3x81ziRTV6Q&s' },
      { index: 4, title: 'CSS Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vkYQ-fp4xFS6EK2qy4ntaox3x81ziRTV6Q&s' },
      { index: 5, title: 'CSS Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vkYQ-fp4xFS6EK2qy4ntaox3x81ziRTV6Q&s' },
      { index: 6, title: 'CSS Chiqish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0vkYQ-fp4xFS6EK2qy4ntaox3x81ziRTV6Q&s' },
    ],
    Bootstrap: [
      { index: 1, title: 'Bootstrap Kirish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIblg5VduM-c7Z3hgT6Z2q08NwmtQRLsFLw&s' },
      { index: 2, title: 'Bootstrap Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIblg5VduM-c7Z3hgT6Z2q08NwmtQRLsFLw&s' },
      { index: 3, title: 'Bootstrap Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIblg5VduM-c7Z3hgT6Z2q08NwmtQRLsFLw&s' },
      { index: 4, title: 'Bootstrap Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIblg5VduM-c7Z3hgT6Z2q08NwmtQRLsFLw&s' },
      { index: 5, title: 'Bootstrap Xulos', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIblg5VduM-c7Z3hgT6Z2q08NwmtQRLsFLw&s' },
      { index: 6, title: 'Bootstrap Chiqish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIblg5VduM-c7Z3hgT6Z2q08NwmtQRLsFLw&s' },
    ],
    Tailwind: [
      { index: 1, title: 'Tailwind Kirish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 2, title: 'Tailwind Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 3, title: 'Tailwind Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 4, title: 'Tailwind Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 5, title: 'Tailwind Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 6, title: 'Tailwind Chiqish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
    ],
    Javascript: [
      { index: 1, title: 'JS Kirish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStcLTs7Bk6BMNVhoF_ufFaD8jhN8SSObWwfw&s' },
      { index: 2, title: 'JS Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStcLTs7Bk6BMNVhoF_ufFaD8jhN8SSObWwfw&shttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 3, title: 'JS Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStcLTs7Bk6BMNVhoF_ufFaD8jhN8SSObWwfw&shttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 4, title: 'JS Asosiy mavzu', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStcLTs7Bk6BMNVhoF_ufFaD8jhN8SSObWwfw&shttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 5, title: 'JS Xulosa', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStcLTs7Bk6BMNVhoF_ufFaD8jhN8SSObWwfw&shttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
      { index: 6, title: 'JS Chiqish', link: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStcLTs7Bk6BMNVhoF_ufFaD8jhN8SSObWwfw&shttps://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPkLvgwX3SaEe0WSKXFhnyvZoagDkOaXkG3A&s' },
    ],
    React: [
      { index: 1, title: 'React Kirish', link: 'https://miro.medium.com/v2/resize:fit:1400/1*8a73qJOidd2Ws9AdrijmSQ.png' },
      { index: 2, title: 'React Asosiy mavzu', link: 'https://miro.medium.com/v2/resize:fit:1400/1*8a73qJOidd2Ws9AdrijmSQ.png' },
      { index: 3, title: 'React Xulosa', link: 'https://miro.medium.com/v2/resize:fit:1400/1*8a73qJOidd2Ws9AdrijmSQ.png' },
      { index: 4, title: 'React Asosiy mavzu', link: 'https://miro.medium.com/v2/resize:fit:1400/1*8a73qJOidd2Ws9AdrijmSQ.png' },
      { index: 5, title: 'React Xulosa', link: 'https://miro.medium.com/v2/resize:fit:1400/1*8a73qJOidd2Ws9AdrijmSQ.png' },
      { index: 6, title: 'React Chiqish', link: 'https://miro.medium.com/v2/resize:fit:1400/1*8a73qJOidd2Ws9AdrijmSQ.png' },
    ],
  };
